version: '3.7'
services:
    db-opergel-pedidos:
        container_name: db-opergel-pedidos
        image: mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: pedidos
            MYSQL_USER: pedidos
            MYSQL_PASSWORD: pedidos
        networks:
            - db-opergel-pedidos
    php-opergel-pedidos:
        container_name: php-fpm-opergel-pedidos
        build: ./php-fpm
        ports:
            - "9000:9001"
        volumes:
            - ./projeto:/var/www/projeto:cached
        depends_on: 
            - db-opergel-pedidos
        networks:
            - db-opergel-pedidos
            - php-opergel-pedidos
    nginx-opergel-pedidos:
        container_name: nginx-opergel-pedidos
        build: ./nginx
        ports:
            - "80:80"
        depends_on: 
            - php-opergel-pedidos
        networks:
            - php-opergel-pedidos
        volumes:
            - ./logs/nginx:/var/log/nginx:cached
            - ./projeto:/var/www/projeto:cached
    redis-opergel-pedidos:
        image: redis
        command: redis-server --requirepass 960c3dac4fa81b4204779fd16ad7
        ports:
            - "6379:6379"        
        networks:
            - php-opergel-pedidos     
            - redis-opergel-pedidos   
networks:
    db-opergel-pedidos:
    php-opergel-pedidos:
    redis-opergel-pedidos:    